import { Controller, Post, Body } from '@nestjs/common';
import { StripeService } from 'src/stripe/stripe.service';

@Controller('payment')
export class PaymentController {
  constructor(private readonly stripeService: StripeService) {}

  //   @Post('charge')
  //   async charge(@Body() paymentData: any) {
  //     const stripe = this.stripeService.getStripeClient();

  //     // Use the stripe object to create charges, handle subscriptions, etc.
  //     // Example: Create a charge
  //     const charge = await stripe.charges.create({
  //       amount: paymentData.amount,
  //       currency: 'usd',
  //       source: paymentData.token, // Payment token generated by Stripe.js or Elements
  //       description: 'Payment for order', // Optional description
  //     });

  //     // Handle the charge response as needed
  //     return charge;
  //   }
}
